prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/keycloak.sql
@@application/shared_components/navigation/lists/wizard_listenimport.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/leaflet_draw_css.sql
@@application/shared_components/files/leaflet_awesome_markers_js.sql
@@application/shared_components/files/leaflet_awesome_markers_css.sql
@@application/shared_components/files/leaflet_tilelayer_wmts_js.sql
@@application/shared_components/files/layers_png.sql
@@application/shared_components/files/layers_2x_png.sql
@@application/shared_components/files/font_awesome_min_css.sql
@@application/shared_components/files/green_marker_png.sql
@@application/shared_components/files/blue_marker_png.sql
@@application/shared_components/files/black_marker_png.sql
@@application/shared_components/files/l_control_locate_min_js.sql
@@application/shared_components/files/l_control_locate_min_css.sql
@@application/shared_components/files/yellow_marker_png.sql
@@application/shared_components/files/turf_min_js.sql
@@application/shared_components/files/spritesheet_svg.sql
@@application/shared_components/files/spritesheet_png.sql
@@application/shared_components/files/spritesheet_2x_png.sql
@@application/shared_components/files/red_marker_png.sql
@@application/shared_components/files/purple_marker_png.sql
@@application/shared_components/files/pink_marker_png.sql
@@application/shared_components/files/markers_soft_2x_png.sql
@@application/shared_components/files/markers_shadow_2x_png.sql
@@application/shared_components/files/markers_shadow_png.sql
@@application/shared_components/files/marker_shadow_png.sql
@@application/shared_components/files/marker_icon_png.sql
@@application/shared_components/files/marker_icon_2x_png.sql
@@application/shared_components/files/leaflet_draw_png_css.sql
@@application/shared_components/files/leaflet_draw_js.sql
@@application/shared_components/files/leaflet_css.sql
@@application/shared_components/files/leaflet_js.sql
@@application/shared_components/files/spin_min_js.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/hat_zugriff_auf_app.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/collection_p4_löschen.sql
@@application/shared_components/logic/application_processes/collections_erzeugen.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/ausbaustatus.sql
@@application/shared_components/user_interface/lovs/bandbreite_mindestbandbreite.sql
@@application/shared_components/user_interface/lovs/bandbreite_zielbandbreite_geplant.sql
@@application/shared_components/user_interface/lovs/ja_nein.sql
@@application/shared_components/user_interface/lovs/listenimport_aktion_1.sql
@@application/shared_components/user_interface/lovs/listenimport_aktion_2.sql
@@application/shared_components/user_interface/lovs/listenimport_aktion_5.sql
@@application/shared_components/user_interface/lovs/listenimport_aktion_nop.sql
@@application/shared_components/user_interface/lovs/listenimport_problemkategorie.sql
@@application/shared_components/user_interface/lovs/loeschgruende.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/mandant.sql
@@application/shared_components/user_interface/lovs/markierung_zeitspanne.sql
@@application/shared_components/user_interface/lovs/technologie.sql
@@application/shared_components/user_interface/lovs/vermarktungscluster.sql
@@application/shared_components/user_interface/lovs/wholebuy_partner.sql
@@application/shared_components/user_interface/lovs/wholebuy_partner_nur_telekom.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/standard_without_footer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/js_is_valid_url.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/keycloak.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/security/authentications/sso.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_09999.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_tabelle_vc_hist.sql
@@application/deployment/install/install_sequence_vc_hist_seq.sql
@@application/deployment/install/install_trigger_trg_vc_hist.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
