INSERT INTO VC_HIST (vc_hist_id,
            operation,
            vc_lfd_nr,
            VORHERIGER_STATUS,
            AKTUELLER_STATUS,
            STATUS_AENDERUNGSDATUM,
            VORHERIGER_AUSBAU_PLAN_TERMIN,
            AKTUELLER_AUSBAU_PLAN_TERMIN,
            AUSBAU_PLAN_TERMIN_AENDERUNGSDATUM,
            AENDERUNGSDATUM)
select vc_hist_seq.nextval,
			VERSIONS_OPERATION,
            vc_lfd_nr,
            CASE 
				WHEN VERSIONS_OPERATION = 'U'
					AND COUNT(*) OVER (PARTITION BY vc_lfd_nr) > 1
					AND STATUS <> LAG(STATUS) OVER (PARTITION BY VC_LFD_NR ORDER BY VERSIONS_STARTTIME DESC)
				THEN LAG(STATUS) OVER (PARTITION BY vc_lfd_nr ORDER BY VERSIONS_STARTTIME DESC)
				ELSE NULL 
			END AS VORHERIGER_STATUS,
            STATUS,
			CASE 
				WHEN VERSIONS_OPERATION = 'U'
					AND COUNT(*) OVER (PARTITION BY vc_lfd_nr) > 1
					AND STATUS <> LAG(STATUS) OVER (PARTITION BY VC_LFD_NR ORDER BY VERSIONS_STARTTIME DESC)
				THEN VERSIONS_STARTTIME
				ELSE NULL 
			END as STATUS_AENDERUNGSDATUM,
            CASE 
				WHEN VERSIONS_OPERATION = 'U'
					AND COUNT(*) OVER (PARTITION BY vc_lfd_nr) > 1
					AND AUSBAU_PLAN_TERMIN <> LAG(AUSBAU_PLAN_TERMIN) OVER (PARTITION BY VC_LFD_NR ORDER BY VERSIONS_STARTTIME DESC)
				THEN LAG(AUSBAU_PLAN_TERMIN) OVER (PARTITION BY vc_lfd_nr ORDER BY VERSIONS_STARTTIME DESC)
				ELSE NULL 
			END AS VORHERIGER_AUSBAU_PLAN_TERMIN,
            AUSBAU_PLAN_TERMIN,
			CASE 
				WHEN VERSIONS_OPERATION = 'U'
					AND COUNT(*) OVER (PARTITION BY vc_lfd_nr) > 1
					AND AUSBAU_PLAN_TERMIN <> LAG(AUSBAU_PLAN_TERMIN) OVER (PARTITION BY VC_LFD_NR ORDER BY VERSIONS_STARTTIME DESC)
				THEN VERSIONS_STARTTIME
				ELSE NULL 
			END as AUSBAU_PLAN_TERMIN_AENDERUNGSDATUM,
            VERSIONS_STARTTIME as AENDERUNGSDATUM
FROM VERMARKTUNGSCLUSTER VERSIONS BETWEEN TIMESTAMP TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND TO_TIMESTAMP('2024-11-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
;


-- sqlcl_snapshot {"hash":"6cd53e3990e52e794ef7890b759d15d5660f03ac","type":"APEX_APPLICATION","name":"f1210","schemaName":"APEX_EXPORT_USER"}