UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2561 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=1362 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2941 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=1682 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=3001 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=1804 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=1041 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=648 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=3083 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=3082 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=3081 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=3084 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 1 WHERE VC_LFD_NR=1801 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=1181 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=725 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=821 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 1 WHERE VC_LFD_NR=921 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2541 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2221 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2161 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2144 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2061 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=2041 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=1803 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=3381 AND operation = 'D';
UPDATE VC_HIST SET LOESCHGRUND = 2 WHERE VC_LFD_NR=1861 AND operation = 'D';
;


-- sqlcl_snapshot {"hash":"ee603e0e3a1b27cc9bc33cbf2929f7a2e9ddf030","type":"APEX_APPLICATION","name":"f1210","schemaName":"APEX_EXPORT_USER"}