create table demo.test (
    test_1 number,
    test_2 number
);


-- sqlcl_snapshot {"hash":"b6b5b2431d22c362a005cc3da0e674f13306d5d0","type":"TABLE","name":"TEST","schemaName":"DEMO","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>DEMO</SCHEMA><NAME>TEST</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>TEST_1</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>TEST_2</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM></COL_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}