create table demo.test_3 (
    test_1 number,
    test_2 number
);


-- sqlcl_snapshot {"hash":"fdfbfda71756576a28d1108b9ed22559375528fd","type":"TABLE","name":"TEST_3","schemaName":"DEMO","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>DEMO</SCHEMA><NAME>TEST_3</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>TEST_1</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>TEST_2</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM></COL_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}